# Generated by Django 3.2.8 on 2022-10-09 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('story', models.TextField(default='')),
                ('image_anime', models.ImageField(default='', upload_to='photos/novel')),
                ('anime_type', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('lang', models.CharField(max_length=150)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('genres', models.ManyToManyField(to='main.Genre')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ColNovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.novel')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(default='')),
                ('date', models.CharField(max_length=150)),
                ('chapter', models.CharField(max_length=150)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colnovel')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
