# Generated by Django 3.2.8 on 2022-10-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221009_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='image_anime',
            new_name='img',
        ),
    ]
